theme: jekyll-theme-cayman
title: Are Housing Prices in University Towns Less Affected by Recessions?
author:
  name: Eugene Agronin, PhD 
  email: "eagronin@gmail.com"
  linkedin: "https://www.linkedin.com/in/eagronin"
description: Based on assignments from Introduction to Data Science in Python by University of Michigan on Coursera
